# -*- coding: utf-8 -*-
"""Trabalho 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cdqJu6kDC345dGR3p6oMz0LEY7wXhr3s
"""

import pandas as pd
import numpy as np
from sklearn.semi_supervised import LabelSpreading
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split

# 1. Carregar dataset
df = pd.read_csv("MSG-SPAM.csv")

# 2. Features (características) e rótulos
X = df[["NL_PALAVRA_SUSPEITA", "TAMANHO_EMAIL", "TEM_LINK"]].values
y = df["ROTULO"].values   # alguns estão NaN = não rotulados

# 3. Substituir os NaN por -1 (indica "sem rótulo")
y_semi = np.where(np.isnan(y), -1, y)

# 4. Criar e treinar modelo semissupervisionado
model = LabelSpreading(kernel="knn", n_neighbors=5, alpha=0.2)
model.fit(X, y_semi)

# 5. Fazer predições
y_pred = model.predict(X)

# 6. Avaliar apenas nas instâncias que realmente tinham rótulo
mask_rotulados = y != np.nan
mask_rotulados = ~np.isnan(y)   # pega só os que tinham rótulo real
print(classification_report(y[mask_rotulados], y_pred[mask_rotulados], target_names=["não spam", "spam"]))