# -*- coding: utf-8 -*-
"""Regressão_Linear.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AiUSenFbvY3sqIJDBizUJ8tV7EG15XTJ

##Importação das bibliotecas
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from math import floor
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

"""Importação do dataframe

#https://www.kaggle.com/datasets/szamil/who-suicide-statistics
"""

dados = pd.read_csv('who_suicide_statistics.csv')
dados

"""##Pré-processamento de Dados

Checagem da Tipagem
"""

print(dados.dtypes)

"""Limpeza dos dados"""

def tratamento(string):
  '''Limpa uma string de idade para se adequar ao modelo'''
  age_str_clean = str(string).replace(' years', '').replace('+', '').replace('-', ' ')
  parts = age_str_clean.split()
  if len(parts) == 1:
      lower_bound = int(parts[0])
      if '+' in str(string):
          upper_bound = 100
      else:
          upper_bound = lower_bound
  else:
      lower_bound = int(parts[0])
      upper_bound = int(parts[1])
  return pd.Series([lower_bound, upper_bound])

#Tratamento da coluna sex junto de remoção de valores Nan
dados_tratados = dados.dropna()
dados_tratados['sex'] = dados_tratados['sex'].replace({'male': 0, 'female': 1}) #Conversão de 'male' para 0 e 'female' para 1

#Tratando idade
dados_tratados[['age_min', 'age_max']] = dados_tratados['age'].apply(tratamento)
dados_tratados = dados_tratados.drop('age', axis=1)

#Criação de Dummies para 'country'
dados_tratados = pd.get_dummies(dados_tratados, columns=['country'], drop_first=True)
dados_tratados

"""Redefinição de Saída e Entrada de dados"""

features = ['year', 'sex', 'age_min', 'age_max', 'population'] + [col for col in dados_tratados.columns if 'country_' in str(col)]
entrada = dados_tratados[features]
saida = dados_tratados['suicides_no']

"""Normalização dos Dados"""

scaler = StandardScaler()
entrada = scaler.fit_transform(entrada)
saida = dados_tratados['suicides_no'].reset_index(drop=True)
print(entrada.shape)
print(saida.shape)

"""Separação de dados
(dados de treino e dados de teste)
"""

x_treino, x_teste, y_treino, y_teste = train_test_split(entrada, saida, test_size=0.2, random_state=42)

"""##Criação do Modelo e Treinamento"""

modelo = LinearRegression()
modelo.fit(x_treino, y_treino)

y_pred = modelo.predict(x_teste)

print("Intercepto:", floor(modelo.intercept_))
print("R²:", str(r2_score(y_teste, y_pred))[:4])
print("Erro quadrático médio:", mean_squared_error(y_teste, y_pred))
print("Erro médio absoluto:", str(mean_absolute_error(y_teste, y_pred))[:6])

"""##Representação

Total de Suicidios por Ano
"""

suicidios_por_ano = dados.groupby('year')['suicides_no'].sum()
plt.figure(figsize=(10, 5))
plt.plot(suicidios_por_ano.index, suicidios_por_ano.values, marker='o',color='darkblue')
plt.title('Total de Suicídios por Ano')
plt.xlabel('Ano')
plt.ylabel('Número de Suicídios')
plt.grid(True)
plt.show()

"""Suicídios por Sexo"""

suicidios_por_sexo = dados.groupby('sex')['suicides_no'].sum()
plt.figure(figsize=(6, 4))
suicidios_por_sexo.plot(kind='bar', color=['purple', 'darkblue'])
plt.title('Suicídios por Sexo')
plt.xlabel('Sexo')
plt.ylabel('Número de Suicídios')
plt.show()

"""Suicídios por Faixa Etária"""

suicidios_por_idade = dados.groupby('age')['suicides_no'].sum().sort_values(ascending=True)
plt.figure(figsize=(8, 5))
suicidios_por_idade.plot(kind='bar', color='darkred')
plt.title('Suicídios por Faixa Etária')
plt.xlabel('Faixa Etária')
plt.ylabel('Número de Suicídios')
plt.xticks(rotation=45)
plt.show()

"""População vs Número de Suicídios"""

plt.figure(figsize=(8, 5))
plt.scatter(dados['population'], dados['suicides_no'], alpha=0.3)
plt.title('População vs Número de Suicídios')
plt.xlabel('População')
plt.ylabel('Suicídios')
plt.grid(True)
plt.show()

plt.figure(figsize=(10, 5))
plt.hist(dados['suicides_no'], bins=50, color='purple', edgecolor='black')
plt.title('Distribuição do Número de Suicídios')
plt.xlabel('Suicídios')
plt.ylabel('Frequência')
plt.grid(True)
plt.show()